import {
  CityAnalyticsSummary,
  CivicNotification,
  Complaint,
  ComplaintCluster,
  UserProfile,
  WorkOrder,
} from '@/types';

export const DEMO_USERS: Record<string, UserProfile> = {
  CITIZEN: {
    uid: 'demo-citizen-1',
    email: 'priya.citizen@civicai.org',
    displayName: 'Priya Ramanathan',
    phoneNumber: '+91 98401 23456',
    role: 'CITIZEN',
    organizationId: 'org-chn-corp',
    wardId: 'Ward 102',
    areaId: 'Anna Nagar West',
    avatarUrl: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80',
    createdAt: '2026-01-10T10:00:00Z',
  },
  AREA_OFFICER: {
    uid: 'demo-officer-1',
    email: 'rajesh.officer@civicai.org',
    displayName: 'Rajesh Kumar',
    phoneNumber: '+91 94440 12890',
    role: 'AREA_OFFICER',
    organizationId: 'org-chn-corp',
    wardId: 'Ward 102',
    areaId: 'Anna Nagar West',
    departmentId: 'Municipal Roads & Infrastructure',
    badgeNumber: 'AO-W102-441',
    avatarUrl: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&auto=format&fit=crop&q=80',
    createdAt: '2025-06-15T09:00:00Z',
  },
  DEPARTMENT_OFFICER: {
    uid: 'demo-dept-officer-1',
    email: 'kavitha.dept@civicai.org',
    displayName: 'Kavitha Sundaram',
    phoneNumber: '+91 94441 55670',
    role: 'DEPARTMENT_OFFICER',
    organizationId: 'org-chn-corp',
    zoneId: 'Zone 8 (Central)',
    departmentId: 'Municipal Roads & Infrastructure',
    badgeNumber: 'DO-RDS-089',
    avatarUrl: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=150&auto=format&fit=crop&q=80',
    createdAt: '2025-04-12T09:00:00Z',
  },
  SUPERVISOR: {
    uid: 'demo-supervisor-1',
    email: 'sundararajan.sup@civicai.org',
    displayName: 'M. Sundararajan',
    phoneNumber: '+91 98840 99881',
    role: 'SUPERVISOR',
    organizationId: 'org-chn-corp',
    zoneId: 'Zone 8 (Central)',
    badgeNumber: 'SUP-ZN8-012',
    avatarUrl: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150&auto=format&fit=crop&q=80',
    createdAt: '2024-11-20T08:30:00Z',
  },
  DISTRICT_MANAGER: {
    uid: 'demo-manager-1',
    email: 'arunkumar.ias@civicai.org',
    displayName: 'Dr. A. Arunkumar IAS',
    phoneNumber: '+91 94450 00001',
    role: 'DISTRICT_MANAGER',
    organizationId: 'org-chn-corp',
    districtId: 'Chennai District',
    badgeNumber: 'DM-CHN-001',
    avatarUrl: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=150&auto=format&fit=crop&q=80',
    createdAt: '2024-01-01T08:00:00Z',
  },
  FIELD_TEAM: {
    uid: 'demo-field-1',
    email: 'murugan.field@civicai.org',
    displayName: 'Murugan (Team Bravo Lead)',
    phoneNumber: '+91 97890 11223',
    role: 'FIELD_TEAM',
    organizationId: 'org-chn-corp',
    departmentId: 'Municipal Roads & Infrastructure',
    badgeNumber: 'FT-RD-BRAVO',
    avatarUrl: 'https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?w=150&auto=format&fit=crop&q=80',
    createdAt: '2025-08-01T07:30:00Z',
  },
  ADMIN: {
    uid: 'demo-admin-1',
    email: 'admin@civicai.org',
    displayName: 'System Administrator',
    role: 'ADMIN',
    organizationId: 'org-chn-corp',
    badgeNumber: 'ADM-SYS-999',
    avatarUrl: 'https://images.unsplash.com/photo-1492562080023-ab3db95bfbce?w=150&auto=format&fit=crop&q=80',
    createdAt: '2024-01-01T00:00:00Z',
  },
};

export const INITIAL_COMPLAINTS: Complaint[] = [
  {
    id: 'CIV-2026-001245',
    citizenId: 'demo-citizen-1',
    citizenName: 'Priya Ramanathan',
    citizenPhone: '+91 98401 23456',
    organizationId: 'org-chn-corp',
    category: 'Road',
    description: 'Large deep pothole with loose gravel near 2nd Avenue junction. Multiple two-wheeler skids reported during peak hours.',
    landmark: 'Opposite Roundtana Metro Station Exit B',
    imageUrls: [
      'https://images.unsplash.com/photo-1515162816999-a0c47dc192f7?w=800&auto=format&fit=crop&q=80',
    ],
    location: {
      latitude: 13.0850,
      longitude: 80.2101,
      readableAddress: '2nd Avenue, Anna Nagar West, Chennai',
      area: 'Anna Nagar West',
      ward: 'Ward 102',
      zone: 'Zone 8 (Central)',
      district: 'Chennai District',
    },
    areaId: 'Anna Nagar West',
    wardId: 'Ward 102',
    zoneId: 'Zone 8 (Central)',
    districtId: 'Chennai District',
    aiAnalysis: {
      issueType: 'Road Damage',
      category: 'Road',
      severity: 'HIGH',
      confidence: 0.91,
      detectedDescription: 'Large pothole affecting road surface with deep sub-base exposure and acute hazard for vehicular stability.',
      suggestedDepartment: 'Municipal Roads & Infrastructure',
      suggestedPriority: 'HIGH',
      tags: ['pothole', 'structural_surface_defect', 'two_wheeler_hazard', 'traffic_choke'],
      reasoning: 'Visual inspection confirms asphalt crater depth exceeding 10cm, requiring immediate bituminous aggregate filling.',
      detectedAt: '2026-09-28T09:15:00Z',
    },
    priority: 'HIGH',
    priorityScore: 88,
    departmentId: 'Municipal Roads & Infrastructure',
    departmentName: 'Municipal Roads & Infrastructure',
    assignedOfficerId: 'demo-officer-1',
    assignedOfficerName: 'Rajesh Kumar (Area Officer)',
    previousOfficerName: 'Rajesh Kumar (Area Officer)',
    status: 'ESCALATED',
    escalationLevel: 2,
    escalationReason: 'Escalated because response deadline was exceeded (SLA 24 hours elapsed without officer acknowledgement).',
    createdAt: '2026-09-28T09:12:00Z',
    updatedAt: '2026-09-29T10:15:00Z',
    responseDeadline: '2026-09-29T09:12:00Z', // In the past -> Overdue!
    resolutionDeadline: '2026-10-02T18:00:00Z',
    statusHistory: [
      {
        status: 'SUBMITTED',
        timestamp: '2026-09-28T09:12:00Z',
        updatedBy: 'demo-citizen-1',
        actorRole: 'CITIZEN',
        actorName: 'Priya Ramanathan',
        notes: 'Citizen submitted grievance via Mobile Web with camera evidence.',
        escalationLevel: 0,
      },
      {
        status: 'UNDER_REVIEW',
        timestamp: '2026-09-28T09:15:00Z',
        updatedBy: 'system-ai',
        actorRole: 'ADMIN',
        actorName: 'Google Gemini 2.0 Civic Engine',
        notes: 'AI auto-classification verified: Road Damage with 91% confidence score. Routed to Ward 102 queue.',
        escalationLevel: 1,
      },
      {
        status: 'ASSIGNED',
        timestamp: '2026-09-28T09:16:00Z',
        updatedBy: 'system-router',
        actorRole: 'ADMIN',
        actorName: 'CivicAI Automated Area Dispatcher',
        notes: 'Assigned to Area Officer Rajesh Kumar (Ward 102). 24h SLA countdown initiated.',
        escalationLevel: 1,
      },
      {
        status: 'ESCALATED',
        timestamp: '2026-09-29T09:13:00Z',
        updatedBy: 'system-sla-daemon',
        actorRole: 'ADMIN',
        actorName: 'CivicAI SLA Escalation Engine',
        notes: 'Response deadline exceeded. Automatically escalated from Level 1 (Area Officer) to Level 2 (Department Officer Kavitha Sundaram).',
        escalationLevel: 2,
      },
    ],
  },
  {
    id: 'CIV-2026-001246',
    citizenId: 'demo-citizen-1',
    citizenName: 'Priya Ramanathan',
    citizenPhone: '+91 98401 23456',
    organizationId: 'org-chn-corp',
    category: 'Drainage',
    description: 'Heavy sewage backflow flooding entire cross-street near 4th Main Road, Anna Nagar West. Pedestrian path completely submerged.',
    landmark: 'Behind Anna Nagar West Bus Terminus',
    imageUrls: [
      'https://images.unsplash.com/photo-1541888946425-d0fbb1861564?w=800&auto=format&fit=crop&q=80',
    ],
    location: {
      latitude: 13.0862,
      longitude: 80.2085,
      readableAddress: '4th Main Road, Anna Nagar West, Chennai',
      area: 'Anna Nagar West',
      ward: 'Ward 102',
      zone: 'Zone 8 (Central)',
      district: 'Chennai District',
    },
    areaId: 'Anna Nagar West',
    wardId: 'Ward 102',
    zoneId: 'Zone 8 (Central)',
    districtId: 'Chennai District',
    aiAnalysis: {
      issueType: 'Sewage Drainage Flood',
      category: 'Drainage',
      severity: 'CRITICAL',
      confidence: 0.96,
      detectedDescription: 'Effluent backflow detected from municipal inspection chamber. Severe biological contamination hazard.',
      suggestedDepartment: 'Sanitation & Drainage Operations',
      suggestedPriority: 'CRITICAL',
      tags: ['sewage_overflow', 'biohazard', 'anna_nagar_cluster'],
      detectedAt: '2026-09-29T10:00:00Z',
    },
    priority: 'CRITICAL',
    priorityScore: 98,
    departmentId: 'Sanitation & Drainage Operations',
    departmentName: 'Sanitation & Drainage Operations',
    assignedOfficerId: 'demo-officer-1',
    assignedOfficerName: 'Rajesh Kumar (Area Officer)',
    status: 'SUBMITTED',
    escalationLevel: 1,
    createdAt: '2026-09-29T09:55:00Z',
    updatedAt: '2026-09-29T10:05:00Z',
    responseDeadline: '2026-09-29T21:55:00Z',
    resolutionDeadline: '2026-09-30T21:55:00Z',
    statusHistory: [
      {
        status: 'SUBMITTED',
        timestamp: '2026-09-29T09:55:00Z',
        updatedBy: 'demo-citizen-1',
        actorRole: 'CITIZEN',
        actorName: 'Priya Ramanathan',
        notes: 'Submitted via Mobile Web with Live Geotag Camera.',
        escalationLevel: 0,
      },
    ],
  },
  {
    id: 'CIV-2026-001247',
    citizenId: 'demo-citizen-4',
    citizenName: 'Suresh Venkatesh',
    citizenPhone: '+91 98402 88771',
    organizationId: 'org-chn-corp',
    category: 'Water',
    description: 'Underground high pressure potable water main burst causing continuous erosion of road shoulder, Anna Nagar West.',
    landmark: 'Near 6th Avenue Post Office',
    imageUrls: [
      'https://images.unsplash.com/photo-1584467735871-8e85353a8413?w=800&auto=format&fit=crop&q=80',
    ],
    location: {
      latitude: 13.0841,
      longitude: 80.2120,
      readableAddress: '6th Avenue, Anna Nagar West, Chennai',
      area: 'Anna Nagar West',
      ward: 'Ward 102',
      zone: 'Zone 8 (Central)',
      district: 'Chennai District',
    },
    areaId: 'Anna Nagar West',
    wardId: 'Ward 102',
    zoneId: 'Zone 8 (Central)',
    districtId: 'Chennai District',
    aiAnalysis: {
      issueType: 'Water Main Rupture',
      category: 'Water',
      severity: 'CRITICAL',
      confidence: 0.94,
      detectedDescription: 'Massive potable water leakage eroding road sub-base. Risk of structural sinkhole formation.',
      suggestedDepartment: 'Metro Water & Sewerage Board',
      suggestedPriority: 'CRITICAL',
      tags: ['pipe_burst', 'water_loss', 'sinkhole_risk'],
      detectedAt: '2026-09-29T11:20:00Z',
    },
    priority: 'CRITICAL',
    priorityScore: 95,
    departmentId: 'Metro Water & Sewerage Board',
    departmentName: 'Metro Water & Sewerage Board',
    assignedOfficerId: 'demo-officer-1',
    assignedOfficerName: 'Rajesh Kumar (Area Officer)',
    status: 'SUBMITTED',
    escalationLevel: 1,
    createdAt: '2026-09-29T11:15:00Z',
    updatedAt: '2026-09-29T11:25:00Z',
    responseDeadline: '2026-09-29T23:15:00Z',
    resolutionDeadline: '2026-09-30T23:15:00Z',
    statusHistory: [
      {
        status: 'SUBMITTED',
        timestamp: '2026-09-29T11:15:00Z',
        updatedBy: 'demo-citizen-4',
        actorRole: 'CITIZEN',
        actorName: 'Suresh Venkatesh',
        notes: 'Submitted via CivicAI with GPS camera verification.',
        escalationLevel: 0,
      },
    ],
  },
  {
    id: 'CIV-2026-001248',
    citizenId: 'demo-citizen-5',
    citizenName: 'Anand Chandrasekar',
    citizenPhone: '+91 97911 34567',
    organizationId: 'org-chn-corp',
    category: 'Road',
    description: 'Cracked asphalt and exposed manhole rim creating dangerous obstruction on 2nd Avenue, Anna Nagar West.',
    landmark: 'Near Roundtana Traffic Signal',
    imageUrls: [
      'https://images.unsplash.com/photo-1515162816999-a0c47dc192f7?w=800&auto=format&fit=crop&q=80',
    ],
    location: {
      latitude: 13.0855,
      longitude: 80.2098,
      readableAddress: '2nd Avenue Roundtana, Anna Nagar West, Chennai',
      area: 'Anna Nagar West',
      ward: 'Ward 102',
      zone: 'Zone 8 (Central)',
      district: 'Chennai District',
    },
    areaId: 'Anna Nagar West',
    wardId: 'Ward 102',
    zoneId: 'Zone 8 (Central)',
    districtId: 'Chennai District',
    aiAnalysis: {
      issueType: 'Road Surface Defect',
      category: 'Road',
      severity: 'HIGH',
      confidence: 0.92,
      detectedDescription: 'Damaged pavement perimeter around inspection chamber with sharp asphalt edges.',
      suggestedDepartment: 'Municipal Roads & Infrastructure',
      suggestedPriority: 'HIGH',
      tags: ['manhole_rim', 'pavement_defect', 'traffic_risk'],
      detectedAt: '2026-09-29T12:00:00Z',
    },
    priority: 'HIGH',
    priorityScore: 89,
    departmentId: 'Municipal Roads & Infrastructure',
    departmentName: 'Municipal Roads & Infrastructure',
    assignedOfficerId: 'demo-officer-1',
    assignedOfficerName: 'Rajesh Kumar (Area Officer)',
    status: 'SUBMITTED',
    escalationLevel: 1,
    createdAt: '2026-09-29T11:50:00Z',
    updatedAt: '2026-09-29T12:05:00Z',
    responseDeadline: '2026-09-30T11:50:00Z',
    resolutionDeadline: '2026-10-01T11:50:00Z',
    statusHistory: [
      {
        status: 'SUBMITTED',
        timestamp: '2026-09-29T11:50:00Z',
        updatedBy: 'demo-citizen-5',
        actorRole: 'CITIZEN',
        actorName: 'Anand Chandrasekar',
        notes: 'Submitted via CivicAI.',
        escalationLevel: 0,
      },
    ],
  },
  {
    id: 'CIV-2026-001289',
    citizenId: 'demo-citizen-2',
    citizenName: 'Karthik Subramanian',
    citizenPhone: '+91 98410 77654',
    organizationId: 'org-chn-corp',
    category: 'Drainage',
    description: 'Sewage manhole overflow spreading foul blackwater into pedestrian footpath near Panagal Park.',
    landmark: 'Near Usman Road flyover pillar 14',
    imageUrls: [
      'https://images.unsplash.com/photo-1541888946425-d0fbb1861564?w=800&auto=format&fit=crop&q=80',
    ],
    location: {
      latitude: 13.0418,
      longitude: 80.2341,
      readableAddress: 'South Usman Road, T. Nagar, Chennai',
      area: 'T. Nagar Commercial',
      ward: 'Ward 114',
      zone: 'Zone 10 (South)',
      district: 'Chennai District',
    },
    areaId: 'T. Nagar Commercial',
    wardId: 'Ward 114',
    zoneId: 'Zone 10 (South)',
    districtId: 'Chennai District',
    aiAnalysis: {
      issueType: 'Drainage Overflow',
      category: 'Drainage',
      severity: 'CRITICAL',
      confidence: 0.95,
      detectedDescription: 'Raw sewage effluent discharge over public walkway with acute public health contamination risk.',
      suggestedDepartment: 'Sanitation & Drainage Operations',
      suggestedPriority: 'CRITICAL',
      tags: ['sanitation', 'sewage_leak', 'pedestrian_hazard', 'health_advisory'],
      detectedAt: '2026-09-29T14:30:00Z',
    },
    priority: 'CRITICAL',
    priorityScore: 96,
    departmentId: 'Sanitation & Drainage Operations',
    departmentName: 'Sanitation & Drainage Operations',
    assignedOfficerId: 'demo-officer-1',
    assignedOfficerName: 'Rajesh Kumar (Area Officer)',
    status: 'ASSIGNED',
    escalationLevel: 1,
    createdAt: '2026-09-29T14:28:00Z',
    updatedAt: '2026-09-29T14:32:00Z',
    responseDeadline: '2026-09-30T02:28:00Z', // In 5 hours
    resolutionDeadline: '2026-09-30T14:28:00Z',
    statusHistory: [
      {
        status: 'SUBMITTED',
        timestamp: '2026-09-29T14:28:00Z',
        updatedBy: 'demo-citizen-2',
        actorRole: 'CITIZEN',
        actorName: 'Karthik Subramanian',
        notes: 'Submitted via CivicAI Citizen Portal.',
        escalationLevel: 0,
      },
      {
        status: 'ASSIGNED',
        timestamp: '2026-09-29T14:30:00Z',
        updatedBy: 'system-router',
        actorRole: 'ADMIN',
        actorName: 'CivicAI Dispatcher',
        notes: 'Tagged Critical: 12h resolution SLA active.',
        escalationLevel: 1,
      },
    ],
  },
  {
    id: 'CIV-2026-001302',
    citizenId: 'demo-citizen-1',
    citizenName: 'Priya Ramanathan',
    citizenPhone: '+91 98401 23456',
    organizationId: 'org-chn-corp',
    category: 'Water',
    description: 'Major underground pipeline burst pumping high-pressure potable water onto main carriageway.',
    landmark: 'Near Gandhi Nagar 3rd Main Road',
    imageUrls: [
      'https://images.unsplash.com/photo-1584467735871-8e85353a8413?w=800&auto=format&fit=crop&q=80',
    ],
    location: {
      latitude: 13.0067,
      longitude: 80.2575,
      readableAddress: 'Gandhi Nagar 3rd Main, Adyar, Chennai',
      area: 'Adyar Canal Corridor',
      ward: 'Ward 173',
      zone: 'Zone 13 (South-East)',
      district: 'Chennai District',
    },
    areaId: 'Adyar Canal Corridor',
    wardId: 'Ward 173',
    zoneId: 'Zone 13 (South-East)',
    districtId: 'Chennai District',
    aiAnalysis: {
      issueType: 'Water Main Burst',
      category: 'Water',
      severity: 'CRITICAL',
      confidence: 0.93,
      detectedDescription: 'Pressurized water transmission line rupture causing substantial water wastage and road erosion.',
      suggestedDepartment: 'Metro Water & Sewerage Board',
      suggestedPriority: 'CRITICAL',
      tags: ['pipe_burst', 'water_wastage', 'subsurface_leak'],
      detectedAt: '2026-09-29T11:00:00Z',
    },
    priority: 'CRITICAL',
    priorityScore: 92,
    departmentId: 'Metro Water & Sewerage Board',
    departmentName: 'Metro Water & Sewerage Board',
    assignedOfficerId: 'demo-supervisor-1',
    assignedOfficerName: 'M. Sundararajan (Supervisor)',
    fieldTeamId: 'demo-field-1',
    fieldTeamName: 'Murugan (Team Bravo Lead)',
    status: 'IN_PROGRESS',
    escalationLevel: 3,
    escalationReason: 'Escalated to Zonal Supervisor due to multiple citizen reports and critical water loss volume.',
    createdAt: '2026-09-29T10:55:00Z',
    updatedAt: '2026-09-29T15:10:00Z',
    responseDeadline: '2026-09-29T14:55:00Z',
    resolutionDeadline: '2026-09-30T06:00:00Z',
    statusHistory: [
      {
        status: 'SUBMITTED',
        timestamp: '2026-09-29T10:55:00Z',
        updatedBy: 'demo-citizen-1',
        actorRole: 'CITIZEN',
        actorName: 'Priya Ramanathan',
        escalationLevel: 0,
      },
      {
        status: 'ESCALATED',
        timestamp: '2026-09-29T12:00:00Z',
        updatedBy: 'demo-dept-officer-1',
        actorRole: 'DEPARTMENT_OFFICER',
        actorName: 'Kavitha Sundaram',
        notes: 'Elevated to Level 3 Supervisor for immediate rapid emergency field crew mobilization.',
        escalationLevel: 3,
      },
      {
        status: 'IN_PROGRESS',
        timestamp: '2026-09-29T13:30:00Z',
        updatedBy: 'demo-field-1',
        actorRole: 'FIELD_TEAM',
        actorName: 'Murugan (Team Bravo Lead)',
        notes: 'Field crew arrived on site with suction pump and replacement cast iron collar.',
        escalationLevel: 3,
      },
    ],
  },
  {
    id: 'CIV-2026-001340',
    citizenId: 'demo-citizen-3',
    citizenName: 'Deepa Natarajan',
    organizationId: 'org-chn-corp',
    category: 'Street Light',
    description: 'Continuous stretch of 5 LED street lights non-functional creating dangerous dark zone.',
    landmark: 'Between Velachery Lake park and inner ring road',
    imageUrls: [
      'https://images.unsplash.com/photo-1509114397022-ed747cca3f65?w=800&auto=format&fit=crop&q=80',
    ],
    location: {
      latitude: 12.9759,
      longitude: 80.2212,
      readableAddress: 'Inner Ring Road, Velachery, Chennai',
      area: 'Velachery Bypass Road',
      ward: 'Ward 178',
      zone: 'Zone 14 (South)',
      district: 'Chennai District',
    },
    areaId: 'Velachery Bypass Road',
    wardId: 'Ward 178',
    zoneId: 'Zone 14 (South)',
    districtId: 'Chennai District',
    aiAnalysis: {
      issueType: 'Street Lighting Failure',
      category: 'Street Light',
      severity: 'MEDIUM',
      confidence: 0.89,
      detectedDescription: 'Non-illuminated lighting infrastructure spanning approx 150m linear pedestrian stretch.',
      suggestedDepartment: 'Electrical Lighting Maintenance',
      suggestedPriority: 'MEDIUM',
      tags: ['lighting', 'public_safety', 'electrical_circuit'],
      detectedAt: '2026-09-29T18:00:00Z',
    },
    priority: 'MEDIUM',
    priorityScore: 64,
    departmentId: 'Electrical Lighting Maintenance',
    departmentName: 'Electrical Lighting Maintenance',
    assignedOfficerId: 'demo-officer-1',
    assignedOfficerName: 'Rajesh Kumar (Area Officer)',
    status: 'SUBMITTED',
    escalationLevel: 1,
    createdAt: '2026-09-29T17:58:00Z',
    updatedAt: '2026-09-29T18:02:00Z',
    responseDeadline: '2026-09-30T17:58:00Z',
    resolutionDeadline: '2026-10-01T17:58:00Z',
    statusHistory: [
      {
        status: 'SUBMITTED',
        timestamp: '2026-09-29T17:58:00Z',
        updatedBy: 'demo-citizen-3',
        actorRole: 'CITIZEN',
        actorName: 'Deepa Natarajan',
        escalationLevel: 0,
      },
    ],
  },
  {
    id: 'CIV-2026-001190',
    citizenId: 'demo-citizen-1',
    citizenName: 'Priya Ramanathan',
    citizenPhone: '+91 98401 23456',
    organizationId: 'org-chn-corp',
    category: 'Waste',
    description: 'Heavy overflow of community waste bin with litter scattered into storm drains.',
    landmark: 'Corner of North Mada Street, near Temple tank',
    imageUrls: [
      'https://images.unsplash.com/photo-1530587191325-3db32d826c18?w=800&auto=format&fit=crop&q=80',
    ],
    location: {
      latitude: 13.0336,
      longitude: 80.2678,
      readableAddress: 'North Mada Street, Mylapore, Chennai',
      area: 'Mylapore Heritage Zone',
      ward: 'Ward 121',
      zone: 'Zone 9 (Central-East)',
      district: 'Chennai District',
    },
    areaId: 'Mylapore Heritage Zone',
    wardId: 'Ward 121',
    zoneId: 'Zone 9 (Central-East)',
    districtId: 'Chennai District',
    aiAnalysis: {
      issueType: 'Garbage Accumulation',
      category: 'Waste',
      severity: 'MEDIUM',
      confidence: 0.94,
      detectedDescription: 'Municipal bin overflow with organic and dry solid waste requiring compactor dispatch.',
      suggestedDepartment: 'Solid Waste Management',
      suggestedPriority: 'MEDIUM',
      tags: ['waste_overflow', 'sanitation_bins', 'hygiene'],
      detectedAt: '2026-09-27T08:30:00Z',
    },
    priority: 'MEDIUM',
    priorityScore: 71,
    departmentId: 'Solid Waste Management',
    departmentName: 'Solid Waste Management',
    assignedOfficerId: 'demo-officer-1',
    assignedOfficerName: 'Rajesh Kumar (Area Officer)',
    fieldTeamId: 'demo-field-1',
    fieldTeamName: 'Murugan (Team Bravo Lead)',
    status: 'RESOLVED',
    escalationLevel: 1,
    createdAt: '2026-09-27T08:20:00Z',
    updatedAt: '2026-09-27T16:45:00Z',
    responseDeadline: '2026-09-28T08:20:00Z',
    resolutionDeadline: '2026-09-28T16:00:00Z',
    resolvedAt: '2026-09-27T16:45:00Z',
    resolutionEvidence: {
      beforeImageUrl: 'https://images.unsplash.com/photo-1530587191325-3db32d826c18?w=800&auto=format&fit=crop&q=80',
      afterImageUrl: 'https://images.unsplash.com/photo-1582407947304-fd86f028f716?w=800&auto=format&fit=crop&q=80',
      notes: 'Sanitation Compactor Unit 4 completed 100% waste clearance, swept perimeter and disinfected with bleaching powder.',
      resolvedAt: '2026-09-27T16:45:00Z',
      verifiedBy: 'Rajesh Kumar (Area Officer Ward 102)',
      fieldTeamId: 'demo-field-1',
      fieldTeamName: 'Murugan (Team Bravo Lead)',
    },
    statusHistory: [
      {
        status: 'SUBMITTED',
        timestamp: '2026-09-27T08:20:00Z',
        updatedBy: 'demo-citizen-1',
        actorRole: 'CITIZEN',
        actorName: 'Priya Ramanathan',
        escalationLevel: 0,
      },
      {
        status: 'ASSIGNED',
        timestamp: '2026-09-27T09:00:00Z',
        updatedBy: 'demo-officer-1',
        actorRole: 'AREA_OFFICER',
        actorName: 'Rajesh Kumar',
        notes: 'Dispatched Solid Waste Compactor crew.',
        escalationLevel: 1,
      },
      {
        status: 'IN_PROGRESS',
        timestamp: '2026-09-27T14:10:00Z',
        updatedBy: 'demo-field-1',
        actorRole: 'FIELD_TEAM',
        actorName: 'Murugan (Team Bravo Lead)',
        notes: 'Work started on site.',
        escalationLevel: 1,
      },
      {
        status: 'RESOLVED',
        timestamp: '2026-09-27T16:45:00Z',
        updatedBy: 'demo-field-1',
        actorRole: 'FIELD_TEAM',
        actorName: 'Murugan (Team Bravo Lead)',
        notes: 'Evidence photos uploaded and verified by Area Officer.',
        escalationLevel: 1,
      },
    ],
  },
  {
    id: 'CIV-2026-001255',
    citizenId: 'demo-citizen-1',
    citizenName: 'Karthik Subramanian',
    citizenPhone: '+91 94431 55678',
    organizationId: 'org-cbe-corp',
    category: 'Road',
    description: 'Cracked concrete road divider and damaged bitumen surface along Cross Cut Road near Gandhipuram junction.',
    landmark: 'Near Gandhipuram Central Bus Stand Platform 2',
    imageUrls: [
      'https://images.unsplash.com/photo-1515162816999-a0c47dc192f7?w=800&auto=format&fit=crop&q=80',
    ],
    location: {
      latitude: 11.0168,
      longitude: 76.9558,
      readableAddress: 'Cross Cut Road, Gandhipuram, Coimbatore - 641012',
      area: 'Gandhipuram Central',
      ward: 'Ward 32',
      zone: 'Central Zone',
      district: 'Coimbatore',
      municipality: 'Coimbatore City Municipal Corporation',
    },
    areaId: 'Gandhipuram Central',
    wardId: 'Ward 32',
    zoneId: 'Central Zone',
    districtId: 'Coimbatore',
    aiAnalysis: {
      issueType: 'Surface & Divider Damage',
      category: 'Road',
      severity: 'HIGH',
      confidence: 0.93,
      detectedDescription: 'Displaced concrete curb divider causing lane obstruction during Coimbatore peak traffic.',
      suggestedDepartment: 'Coimbatore City Engineering Dept',
      suggestedPriority: 'HIGH',
      tags: ['road_curb', 'traffic_obstruction', 'coimbatore_corporation'],
      detectedAt: '2026-09-29T08:00:00Z',
    },
    priority: 'HIGH',
    priorityScore: 89,
    departmentId: 'Coimbatore City Engineering Dept',
    departmentName: 'Coimbatore City Engineering Dept',
    assignedOfficerId: 'officer-cbe-32',
    assignedOfficerName: 'Senthil Nathan (Ward 32 Officer)',
    status: 'IN_PROGRESS',
    escalationLevel: 1,
    createdAt: '2026-09-29T08:00:00Z',
    updatedAt: '2026-09-29T09:30:00Z',
    responseDeadline: '2026-09-30T08:00:00Z',
    resolutionDeadline: '2026-10-02T18:00:00Z',
    statusHistory: [
      {
        status: 'SUBMITTED',
        timestamp: '2026-09-29T08:00:00Z',
        updatedBy: 'demo-citizen-1',
        actorRole: 'CITIZEN',
        actorName: 'Karthik Subramanian',
        notes: 'Logged with live camera GPS telemetry.',
        escalationLevel: 0,
      },
      {
        status: 'ASSIGNED',
        timestamp: '2026-09-29T08:05:00Z',
        updatedBy: 'system-ai',
        actorRole: 'ADMIN',
        actorName: 'CivicAI Dispatcher',
        notes: 'Auto-routed to Coimbatore Corporation Central Zone Ward 32.',
        escalationLevel: 1,
      },
      {
        status: 'IN_PROGRESS',
        timestamp: '2026-09-29T09:30:00Z',
        updatedBy: 'officer-cbe-32',
        actorRole: 'AREA_OFFICER',
        actorName: 'Senthil Nathan',
        notes: 'Field crew dispatched for divider realignment.',
        escalationLevel: 1,
      },
    ],
  },
  {
    id: 'CIV-2026-001256',
    citizenId: 'demo-citizen-1',
    citizenName: 'Meenakshi Sundaram',
    citizenPhone: '+91 98421 99102',
    organizationId: 'org-mdu-corp',
    category: 'Water',
    description: 'Underground drinking water feeder pipe breach spilling water continuously onto Simmakkal street.',
    landmark: 'Opposite Simmakkal Roundana & Heritage Circle',
    imageUrls: [
      'https://images.unsplash.com/photo-1584467735871-8e85353a8413?w=800&auto=format&fit=crop&q=80',
    ],
    location: {
      latitude: 9.9252,
      longitude: 78.1198,
      readableAddress: 'Simmakkal Circle, Madurai - 625001',
      area: 'Simmakkal Heritage Circle',
      ward: 'Ward 44',
      zone: 'North Zone',
      district: 'Madurai',
      municipality: 'Madurai City Municipal Corporation',
    },
    areaId: 'Simmakkal Heritage Circle',
    wardId: 'Ward 44',
    zoneId: 'North Zone',
    districtId: 'Madurai',
    aiAnalysis: {
      issueType: 'Potable Water Feeder Breach',
      category: 'Water',
      severity: 'CRITICAL',
      confidence: 0.95,
      detectedDescription: 'High-pressure clean water leakage inundating roadside stalls in commercial center.',
      suggestedDepartment: 'Madurai Corporation Water Works',
      suggestedPriority: 'CRITICAL',
      tags: ['pipe_burst', 'madurai_north', 'heritage_circle'],
      detectedAt: '2026-09-29T10:15:00Z',
    },
    priority: 'CRITICAL',
    priorityScore: 97,
    departmentId: 'Madurai Corporation Water Works',
    departmentName: 'Madurai Corporation Water Works',
    assignedOfficerId: 'officer-mdu-44',
    assignedOfficerName: 'Ramasamy K. (Area Officer)',
    status: 'SUBMITTED',
    escalationLevel: 1,
    createdAt: '2026-09-29T10:15:00Z',
    updatedAt: '2026-09-29T10:15:00Z',
    responseDeadline: '2026-09-29T22:15:00Z',
    resolutionDeadline: '2026-10-01T22:15:00Z',
    statusHistory: [
      {
        status: 'SUBMITTED',
        timestamp: '2026-09-29T10:15:00Z',
        updatedBy: 'demo-citizen-1',
        actorRole: 'CITIZEN',
        actorName: 'Meenakshi Sundaram',
        notes: 'Submitted via CivicAI Citizen Portal with auto-detected Madurai Corporation jurisdiction.',
        escalationLevel: 0,
      },
    ],
  },
  {
    id: 'CIV-2026-001257',
    citizenId: 'demo-citizen-1',
    citizenName: 'Anand Kumar',
    citizenPhone: '+91 97910 44556',
    organizationId: 'org-try-corp',
    category: 'Drainage',
    description: 'Stormwater drain inlet blocked with construction debris, causing water stagnation across Shastri Road.',
    landmark: 'Shastri Road, Thillai Nagar 10th Cross',
    imageUrls: [
      'https://images.unsplash.com/photo-1541888946425-d0fbb1861564?w=800&auto=format&fit=crop&q=80',
    ],
    location: {
      latitude: 10.8285,
      longitude: 78.6854,
      readableAddress: '10th Cross, Thillai Nagar, Tiruchirappalli - 620018',
      area: 'Thillai Nagar West',
      ward: 'Ward 28',
      zone: 'Zone 3 (Golden Rock)',
      district: 'Tiruchirappalli',
      municipality: 'Tiruchirappalli City Municipal Corporation',
    },
    areaId: 'Thillai Nagar West',
    wardId: 'Ward 28',
    zoneId: 'Zone 3 (Golden Rock)',
    districtId: 'Tiruchirappalli',
    aiAnalysis: {
      issueType: 'Stormwater Culvert Blockage',
      category: 'Drainage',
      severity: 'HIGH',
      confidence: 0.92,
      detectedDescription: 'Silt and building rubble choke stormwater culvert. Flood risk during monsoon showers.',
      suggestedDepartment: 'Tiruchirappalli City Sanitation & Drainage',
      suggestedPriority: 'HIGH',
      tags: ['culvert_choke', 'trichy_thillai_nagar', 'drainage'],
      detectedAt: '2026-09-29T07:45:00Z',
    },
    priority: 'HIGH',
    priorityScore: 86,
    departmentId: 'Tiruchirappalli City Sanitation & Drainage',
    departmentName: 'Tiruchirappalli City Sanitation & Drainage',
    assignedOfficerId: 'officer-try-28',
    assignedOfficerName: 'Manickam Pillai',
    status: 'ASSIGNED',
    escalationLevel: 1,
    createdAt: '2026-09-29T07:45:00Z',
    updatedAt: '2026-09-29T07:50:00Z',
    responseDeadline: '2026-09-30T07:45:00Z',
    resolutionDeadline: '2026-10-02T19:45:00Z',
    statusHistory: [
      {
        status: 'SUBMITTED',
        timestamp: '2026-09-29T07:45:00Z',
        updatedBy: 'demo-citizen-1',
        actorRole: 'CITIZEN',
        actorName: 'Anand Kumar',
        notes: 'Reported with GPS camera verification.',
        escalationLevel: 0,
      },
      {
        status: 'ASSIGNED',
        timestamp: '2026-09-29T07:50:00Z',
        updatedBy: 'system-ai',
        actorRole: 'ADMIN',
        actorName: 'CivicAI Engine',
        notes: 'Dispatched to Trichy Corporation Ward 28 supervisor.',
        escalationLevel: 1,
      },
    ],
  },
  {
    id: 'CIV-2026-001258',
    citizenId: 'demo-citizen-1',
    citizenName: 'Selvi Muthusamy',
    citizenPhone: '+91 94860 12398',
    organizationId: 'org-slm-corp',
    category: 'Waste',
    description: 'Unattended municipal solid waste heap overflowing onto main bus bay road, attracting stray cattle.',
    landmark: 'Behind Suramangalam Railway Station East Gate',
    imageUrls: [
      'https://images.unsplash.com/photo-1532996122724-e3c354a0b15b?w=800&auto=format&fit=crop&q=80',
    ],
    location: {
      latitude: 11.6643,
      longitude: 78.1460,
      readableAddress: 'Station Road, Suramangalam, Salem - 636005',
      area: 'Suramangalam / Junction',
      ward: 'Ward 17',
      zone: 'Suramangalam Zone',
      district: 'Salem',
      municipality: 'Salem City Municipal Corporation',
    },
    areaId: 'Suramangalam / Junction',
    wardId: 'Ward 17',
    zoneId: 'Suramangalam Zone',
    districtId: 'Salem',
    aiAnalysis: {
      issueType: 'Solid Waste Accumulation',
      category: 'Waste',
      severity: 'HIGH',
      confidence: 0.94,
      detectedDescription: 'Unsegregated municipal garbage backlog exceeding 48 hours without clearance.',
      suggestedDepartment: 'Salem Corporation Solid Waste Management',
      suggestedPriority: 'HIGH',
      tags: ['garbage_overflow', 'salem_junction', 'hygiene_risk'],
      detectedAt: '2026-09-28T11:00:00Z',
    },
    priority: 'HIGH',
    priorityScore: 91,
    departmentId: 'Salem Corporation Solid Waste Management',
    departmentName: 'Salem Corporation Solid Waste Management',
    assignedOfficerId: 'officer-slm-17',
    assignedOfficerName: 'Periasamy V.',
    status: 'ESCALATED',
    escalationLevel: 2,
    escalationReason: 'Escalated to Salem City Health Officer due to overdue 24h SLA response.',
    createdAt: '2026-09-28T11:00:00Z',
    updatedAt: '2026-09-29T11:05:00Z',
    responseDeadline: '2026-09-29T11:00:00Z',
    resolutionDeadline: '2026-10-01T18:00:00Z',
    statusHistory: [
      {
        status: 'SUBMITTED',
        timestamp: '2026-09-28T11:00:00Z',
        updatedBy: 'demo-citizen-1',
        actorRole: 'CITIZEN',
        actorName: 'Selvi Muthusamy',
        notes: 'Submitted via Mobile Web.',
        escalationLevel: 0,
      },
      {
        status: 'ESCALATED',
        timestamp: '2026-09-29T11:05:00Z',
        updatedBy: 'system-sla-daemon',
        actorRole: 'ADMIN',
        actorName: 'CivicAI SLA Escalation Daemon',
        notes: 'SLA response window breached. Escalated to Level 2 (Salem Municipal Commissioner / Health Officer).',
        escalationLevel: 2,
      },
    ],
  },
  {
    id: 'CIV-2026-001259',
    citizenId: 'demo-citizen-1',
    citizenName: 'Bala Chandran',
    citizenPhone: '+91 99440 88712',
    organizationId: 'org-ten-corp',
    category: 'Street Light',
    description: 'Series of 6 sodium vapour street lights non-functional around Nellaiappar temple car street, plunging road into darkness.',
    landmark: 'East Car Street, Tirunelveli Town',
    imageUrls: [
      'https://images.unsplash.com/photo-1509198397868-475647b2a1e5?w=800&auto=format&fit=crop&q=80',
    ],
    location: {
      latitude: 8.7139,
      longitude: 77.7567,
      readableAddress: 'East Car Street, Tirunelveli Town - 627006',
      area: 'Tirunelveli Town',
      ward: 'Ward 12',
      zone: 'Thachanallur Zone',
      district: 'Tirunelveli',
      municipality: 'Tirunelveli City Municipal Corporation',
    },
    areaId: 'Tirunelveli Town',
    wardId: 'Ward 12',
    zoneId: 'Thachanallur Zone',
    districtId: 'Tirunelveli',
    aiAnalysis: {
      issueType: 'Street Lighting Grid Failure',
      category: 'Street Light',
      severity: 'MEDIUM',
      confidence: 0.90,
      detectedDescription: 'Cluster of non-functioning lighting luminaires creating safety concerns on pedestrian road.',
      suggestedDepartment: 'Tirunelveli Electrical Operations',
      suggestedPriority: 'MEDIUM',
      tags: ['lighting_failure', 'tirunelveli_town', 'car_street'],
      detectedAt: '2026-09-27T19:00:00Z',
    },
    priority: 'MEDIUM',
    priorityScore: 78,
    departmentId: 'Tirunelveli Electrical Operations',
    departmentName: 'Tirunelveli Electrical Operations',
    assignedOfficerId: 'officer-ten-12',
    assignedOfficerName: 'Ganesan S.',
    fieldTeamId: 'field-ten-1',
    fieldTeamName: 'Tirunelveli Electrical Flying Squad',
    status: 'RESOLVED',
    escalationLevel: 1,
    createdAt: '2026-09-27T19:00:00Z',
    updatedAt: '2026-09-28T16:00:00Z',
    responseDeadline: '2026-09-28T19:00:00Z',
    resolutionDeadline: '2026-09-30T19:00:00Z',
    resolvedAt: '2026-09-28T16:00:00Z',
    resolutionEvidence: {
      beforeImageUrl: 'https://images.unsplash.com/photo-1509198397868-475647b2a1e5?w=800&auto=format&fit=crop&q=80',
      afterImageUrl: 'https://images.unsplash.com/photo-1518709268805-4e9042af9f23?w=800&auto=format&fit=crop&q=80',
      notes: 'Fused LED fixtures replaced and circuit breaker reset on East Car Street mast.',
      resolvedAt: '2026-09-28T16:00:00Z',
      fieldTeamId: 'field-ten-1',
      fieldTeamName: 'Tirunelveli Electrical Flying Squad',
    },
    statusHistory: [
      {
        status: 'SUBMITTED',
        timestamp: '2026-09-27T19:00:00Z',
        updatedBy: 'demo-citizen-1',
        actorRole: 'CITIZEN',
        actorName: 'Bala Chandran',
        notes: 'Submitted complaint.',
        escalationLevel: 0,
      },
      {
        status: 'RESOLVED',
        timestamp: '2026-09-28T16:00:00Z',
        updatedBy: 'field-ten-1',
        actorRole: 'FIELD_TEAM',
        actorName: 'Tirunelveli Electrical Flying Squad',
        notes: 'Photographic resolution evidence uploaded and validated.',
        escalationLevel: 1,
      },
    ],
  },
];

export const INITIAL_WORK_ORDERS: WorkOrder[] = [
  {
    id: 'WO-2026-0081',
    complaintId: 'CIV-2026-001245',
    complaintTitle: 'Pothole asphalt filling on 2nd Avenue Roundtana',
    category: 'Road',
    priority: 'HIGH',
    location: {
      latitude: 13.0850,
      longitude: 80.2101,
      readableAddress: '2nd Avenue, Anna Nagar West, Chennai',
      area: 'Anna Nagar West',
      ward: 'Ward 102',
    },
    fieldTeamId: 'demo-field-1',
    fieldTeamName: 'Murugan (Team Bravo Lead)',
    status: 'ASSIGNED',
    assignedDate: '2026-09-29T10:30:00Z',
    deadline: '2026-09-30T16:00:00Z',
    instructions: 'Deploy cold-mix bituminous patch. Ensure roller compaction level is flush with existing asphalt to prevent vehicle damage.',
    beforePhoto: 'https://images.unsplash.com/photo-1515162816999-a0c47dc192f7?w=800&auto=format&fit=crop&q=80',
  },
  {
    id: 'WO-2026-0079',
    complaintId: 'CIV-2026-001302',
    complaintTitle: 'Underground pipeline rupture sealing & clamp replacement',
    category: 'Water',
    priority: 'CRITICAL',
    location: {
      latitude: 13.0067,
      longitude: 80.2575,
      readableAddress: 'Gandhi Nagar 3rd Main, Adyar, Chennai',
      area: 'Adyar Canal Corridor',
      ward: 'Ward 173',
    },
    fieldTeamId: 'demo-field-1',
    fieldTeamName: 'Murugan (Team Bravo Lead)',
    status: 'IN_PROGRESS',
    assignedDate: '2026-09-29T12:30:00Z',
    deadline: '2026-09-30T06:00:00Z',
    instructions: 'Isolate upstream valve valve-A12. Excavate trench to expose flange gasket and mount heavy-duty steel clamp.',
    beforePhoto: 'https://images.unsplash.com/photo-1584467735871-8e85353a8413?w=800&auto=format&fit=crop&q=80',
  },
];

export const INITIAL_HOTSPOTS: ComplaintCluster[] = [
  {
    id: 'cluster-anna-nagar',
    areaName: 'Anna Nagar West',
    ward: 'Ward 102',
    coordinates: { latitude: 13.0850, longitude: 80.2101 },
    totalCount: 61,
    openCount: 27,
    resolvedCount: 34,
    criticalCount: 7,
    topCategory: 'Road',
    categoryBreakdown: {
      'Road': 42,
      'Water': 11,
      'Drainage': 8,
    },
    averageResponseTimeHours: 3.8,
    severityLevel: 'HIGH',
  },
  {
    id: 'cluster-t-nagar',
    areaName: 'T. Nagar Commercial',
    ward: 'Ward 114',
    coordinates: { latitude: 13.0418, longitude: 80.2341 },
    totalCount: 50,
    openCount: 21,
    resolvedCount: 29,
    criticalCount: 9,
    topCategory: 'Drainage',
    categoryBreakdown: {
      'Drainage': 38,
      'Street Light': 15,
      'Waste': 7,
    },
    averageResponseTimeHours: 4.2,
    severityLevel: 'HIGH',
  },
  {
    id: 'cluster-adyar',
    areaName: 'Adyar Canal Corridor',
    ward: 'Ward 173',
    coordinates: { latitude: 13.0067, longitude: 80.2575 },
    totalCount: 36,
    openCount: 14,
    resolvedCount: 22,
    criticalCount: 4,
    topCategory: 'Water',
    categoryBreakdown: {
      'Water': 19,
      'Waste': 12,
      'Public Infrastructure': 5,
    },
    averageResponseTimeHours: 5.1,
    severityLevel: 'MEDIUM',
  },
  {
    id: 'cluster-velachery',
    areaName: 'Velachery Bypass Road',
    ward: 'Ward 178',
    coordinates: { latitude: 12.9759, longitude: 80.2212 },
    totalCount: 34,
    openCount: 18,
    resolvedCount: 16,
    criticalCount: 6,
    topCategory: 'Flooding',
    categoryBreakdown: {
      'Flooding': 24,
      'Road': 9,
      'Street Light': 8,
    },
    averageResponseTimeHours: 4.6,
    severityLevel: 'HIGH',
  },
  {
    id: 'cluster-mylapore',
    areaName: 'Mylapore Heritage Zone',
    ward: 'Ward 121',
    coordinates: { latitude: 13.0336, longitude: 80.2678 },
    totalCount: 23,
    openCount: 4,
    resolvedCount: 19,
    criticalCount: 1,
    topCategory: 'Street Light',
    categoryBreakdown: {
      'Street Light': 12,
      'Waste': 5,
      'Other': 6,
    },
    averageResponseTimeHours: 2.1,
    severityLevel: 'LOW',
  },
  {
    id: 'cluster-kilpauk',
    areaName: 'Kilpauk Medical Enclave',
    ward: 'Ward 104',
    coordinates: { latitude: 13.0805, longitude: 80.2422 },
    totalCount: 28,
    openCount: 9,
    resolvedCount: 19,
    criticalCount: 2,
    topCategory: 'Drainage',
    categoryBreakdown: {
      'Drainage': 16,
      'Electric Infrastructure': 8,
      'Road': 4,
    },
    averageResponseTimeHours: 3.4,
    severityLevel: 'LOW',
  },
  {
    id: 'cluster-cbe-gandhipuram',
    areaName: 'Gandhipuram Central (Coimbatore)',
    ward: 'Ward 32',
    coordinates: { latitude: 11.0168, longitude: 76.9558 },
    totalCount: 48,
    openCount: 19,
    resolvedCount: 29,
    criticalCount: 5,
    topCategory: 'Road',
    categoryBreakdown: {
      'Road': 28,
      'Street Light': 11,
      'Drainage': 9,
    },
    averageResponseTimeHours: 3.2,
    severityLevel: 'HIGH',
  },
  {
    id: 'cluster-mdu-simmakkal',
    areaName: 'Simmakkal Heritage Circle (Madurai)',
    ward: 'Ward 44',
    coordinates: { latitude: 9.9252, longitude: 78.1198 },
    totalCount: 39,
    openCount: 14,
    resolvedCount: 25,
    criticalCount: 4,
    topCategory: 'Water',
    categoryBreakdown: {
      'Water': 24,
      'Waste': 10,
      'Road': 5,
    },
    averageResponseTimeHours: 3.9,
    severityLevel: 'MEDIUM',
  },
  {
    id: 'cluster-try-thillai',
    areaName: 'Thillai Nagar West (Tiruchirappalli)',
    ward: 'Ward 28',
    coordinates: { latitude: 10.8285, longitude: 78.6854 },
    totalCount: 31,
    openCount: 11,
    resolvedCount: 20,
    criticalCount: 3,
    topCategory: 'Drainage',
    categoryBreakdown: {
      'Drainage': 18,
      'Road': 8,
      'Water': 5,
    },
    averageResponseTimeHours: 4.1,
    severityLevel: 'MEDIUM',
  },
  {
    id: 'cluster-slm-junction',
    areaName: 'Suramangalam / Junction (Salem)',
    ward: 'Ward 17',
    coordinates: { latitude: 11.6643, longitude: 78.1460 },
    totalCount: 29,
    openCount: 12,
    resolvedCount: 17,
    criticalCount: 3,
    topCategory: 'Waste',
    categoryBreakdown: {
      'Waste': 17,
      'Street Light': 7,
      'Road': 5,
    },
    averageResponseTimeHours: 4.5,
    severityLevel: 'HIGH',
  },
  {
    id: 'cluster-ten-town',
    areaName: 'Tirunelveli Town (Tirunelveli)',
    ward: 'Ward 12',
    coordinates: { latitude: 8.7139, longitude: 77.7567 },
    totalCount: 25,
    openCount: 6,
    resolvedCount: 19,
    criticalCount: 2,
    topCategory: 'Street Light',
    categoryBreakdown: {
      'Street Light': 15,
      'Drainage': 6,
      'Waste': 4,
    },
    averageResponseTimeHours: 2.8,
    severityLevel: 'LOW',
  },
];

export const INITIAL_NOTIFICATIONS: CivicNotification[] = [
  {
    id: 'notif-1',
    userId: 'demo-citizen-1',
    complaintId: 'CIV-2026-001245',
    type: 'COMPLAINT_ESCALATED',
    title: 'Complaint Escalated to Supervisor',
    message: 'Your complaint CIV-2026-001245 has been escalated because the response deadline was exceeded.',
    read: false,
    createdAt: '2026-09-29T09:14:00Z',
    actionUrl: '/citizen/complaints/CIV-2026-001245',
  },
  {
    id: 'notif-2',
    userId: 'demo-citizen-1',
    complaintId: 'CIV-2026-001302',
    type: 'WORK_STARTED',
    title: 'Field Team Dispatched',
    message: 'Field Team Bravo has initiated work on your reported water pipeline issue CIV-2026-001302.',
    read: false,
    createdAt: '2026-09-29T13:31:00Z',
    actionUrl: '/citizen/complaints/CIV-2026-001302',
  },
  {
    id: 'notif-3',
    userId: 'demo-citizen-1',
    complaintId: 'CIV-2026-001190',
    type: 'COMPLAINT_RESOLVED',
    title: 'Complaint Resolved ✓',
    message: 'Your complaint CIV-2026-001190 has been resolved with before/after photo verification.',
    read: true,
    createdAt: '2026-09-27T16:46:00Z',
    actionUrl: '/citizen/complaints/CIV-2026-001190',
  },
  {
    id: 'notif-4',
    userId: 'demo-officer-1',
    complaintId: 'CIV-2026-001289',
    type: 'OFFICER_ASSIGNED',
    title: 'Critical Issue Assigned (Ward 114)',
    message: 'New critical drainage overflow CIV-2026-001289 requires urgent inspection before SLA deadline.',
    read: false,
    createdAt: '2026-09-29T14:31:00Z',
    actionUrl: '/officer/complaints/CIV-2026-001289',
  },
  {
    id: 'notif-5',
    userId: 'demo-supervisor-1',
    complaintId: 'CIV-2026-001245',
    type: 'COMPLAINT_ESCALATED',
    title: 'Level 2 Escalation Warning',
    message: 'Road damage complaint CIV-2026-001245 in Ward 102 exceeded Area Officer response SLA.',
    read: false,
    createdAt: '2026-09-29T09:15:00Z',
    actionUrl: '/supervisor/complaints/CIV-2026-001245',
  },
];

export const INITIAL_CITY_ANALYTICS: CityAnalyticsSummary = {
  totalComplaints: 232,
  openComplaints: 93,
  criticalIssues: 29,
  escalatedIssues: 14,
  resolvedIssues: 139,
  averageResponseTimeHours: 3.4,
  averageResolutionTimeHours: 28.5,
  resolutionRatePercent: 78.4,
  escalationRatePercent: 6.0,
  categoryDistribution: [
    { category: 'Road', count: 78, percentage: 33.6 },
    { category: 'Drainage', count: 48, percentage: 20.7 },
    { category: 'Water', count: 39, percentage: 16.8 },
    { category: 'Street Light', count: 29, percentage: 12.5 },
    { category: 'Waste', count: 22, percentage: 9.5 },
    { category: 'Flooding', count: 16, percentage: 6.9 },
  ],
  areaDistribution: [
    { area: 'Anna Nagar West', count: 61, open: 27, resolved: 34 },
    { area: 'T. Nagar Commercial', count: 50, open: 21, resolved: 29 },
    { area: 'Adyar Canal Corridor', count: 36, open: 14, resolved: 22 },
    { area: 'Velachery Bypass Road', count: 34, open: 18, resolved: 16 },
    { area: 'Kilpauk Enclave', count: 28, open: 9, resolved: 19 },
    { area: 'Mylapore Heritage', count: 23, open: 4, resolved: 19 },
  ],
  weeklyTrend: [
    { date: 'Mon', submitted: 32, resolved: 28, escalated: 2 },
    { date: 'Tue', submitted: 41, resolved: 35, escalated: 4 },
    { date: 'Wed', submitted: 38, resolved: 30, escalated: 3 },
    { date: 'Thu', submitted: 45, resolved: 39, escalated: 1 },
    { date: 'Fri', submitted: 39, resolved: 36, escalated: 2 },
    { date: 'Sat', submitted: 25, resolved: 21, escalated: 1 },
    { date: 'Sun', submitted: 18, resolved: 16, escalated: 1 },
  ],
};
